[package]
name = "grit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
color-eyre = "0.6"
git2 = { version = "0.20", default-features = false }
ratatui = "0.29"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
which = "7"
base64 = "0.22"
